<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('reviews')->insert([
            'client_customer_id' => 1,
            'client_id' => 1,
            'title' => 'Great event, had lots of fun!',
            'description' => 'Great opportunity to see some wonderful films and new talent...especially love the short films both local and international',
            'rating' => 5,
            'created_at' => Carbon::now(),
        ]);

        DB::table('reviews')->insert([
            'client_customer_id' => 2,
            'client_id' => 2,
            'title' => 'Horrible place would never come back here never ever!!',
            'description' => 'The art was generated by AI and was selling for $1 million bitcoins EACH!',
            'rating' => 1,
            'created_at' => Carbon::now(),
        ]);

        DB::table('reviews')->insert([
            'client_customer_id' => 3,
            'client_id' => 3,
            'title' => 'Great music, food, and people.',
            'description' => 'The waterfront location provides a beautiful backdrop for the main stage to look out on, but this festival is so much more than just a one stage act. There are musical acts all over the city throughout the week that you are able to take in and enjoy.',
            'rating' => 4,
            'created_at' => Carbon::now(),
        ]);
    }
}
